import type { Config } from 'tailwindcss'
import { palette } from './server/utils/palette'

export default {
  content: [
    './app/components/**/*.{vue,js,ts}',
    './app/layouts/**/*.vue',
    './app/pages/**/*.vue',
    './app/app.vue',
    './app.vue',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: [
          'Vazirmatn Variable',
          'Vazirmatn',
          '-apple-system',
          'BlinkMacSystemFont',
          'SF Pro Display',
          'SF Pro Text',
          'Segoe UI',
          'Helvetica Neue',
          'Arial',
          'sans-serif',
        ],
      },
      colors: {
        fd: {
          bg: palette.gray[100],
          primary: palette.brand.primary,
          'primary-light': palette.brand.primaryLight,
          'primary-soft': palette.brand.primarySoft,
          navy: palette.gray[900],
          muted: palette.gray[400],
          success: palette.semantic.success,
          danger: palette.semantic.danger,
          warning: palette.semantic.warning,
        },
        brand: {
          primary: palette.brand.primary,
          'primary-dark': palette.brand.primaryDark,
          orange: palette.brand.accent,
          'orange-dark': palette.brand.accentDark,
          green: palette.semantic.success,
          teal: palette.brand.primaryLight,
          blue: palette.brand.primaryLight,
          indigo: palette.brand.primaryDark,
          pink: palette.semantic.danger,
          purple: palette.brand.primary,
          yellow: palette.semantic.warning,
          gray: palette.gray,
        },
        sz: {
          primary: palette.brand.primary,
          'primary-dark': palette.brand.primaryDark,
          orange: palette.brand.accent,
          'orange-dark': palette.brand.accentDark,
          'orange-soft': palette.brand.accentSoft,
          green: palette.semantic.success,
          teal: palette.brand.primaryLight,
          blue: palette.brand.primaryLight,
          indigo: palette.brand.primaryDark,
          pink: palette.semantic.danger,
          purple: palette.brand.primary,
          yellow: palette.semantic.warning,
          gray: palette.gray,
          'accent-soft': palette.brand.primarySoft,
        },
      },
      borderRadius: {
        ios: '1.25rem',
        'ios-lg': '1.75rem',
        'ios-xl': '2.25rem',
      },
      boxShadow: {
        fd: '0px 18px 40px rgba(68, 64, 60, 0.08)',
        'fd-soft': '0px 8px 24px rgba(68, 64, 60, 0.06)',
        glass: '0 8px 32px rgba(0, 0, 0, 0.08)',
        card: '0 2px 16px rgba(0, 0, 0, 0.06)',
        float: '0 12px 40px rgba(0, 0, 0, 0.12)',
        lifted: '0 18px 50px -12px rgba(30, 58, 95, 0.28)',
        'lifted-soft': '0 16px 40px -16px rgba(0, 0, 0, 0.22)',
      },
      animation: {
        'fade-in': 'fadeIn 0.4s cubic-bezier(0.25, 0.46, 0.45, 0.94)',
        'slide-up': 'slideUp 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94)',
        'fade-up': 'fadeUp 0.55s cubic-bezier(0.22, 1, 0.36, 1) both',
        'scale-pop': 'scalePop 0.35s cubic-bezier(0.34, 1.56, 0.64, 1) both',
        'pulse-soft': 'pulseSoft 2.4s ease-in-out infinite',
        'success-check': 'successCheck 0.5s cubic-bezier(0.34, 1.56, 0.64, 1) both',
        'slide-in': 'slideIn 0.35s cubic-bezier(0.22, 1, 0.36, 1) both',
        'grid-in': 'gridIn 0.45s cubic-bezier(0.22, 1, 0.36, 1) both',
        'icon-bounce': 'iconBounce 0.6s cubic-bezier(0.34, 1.56, 0.64, 1) both',
        'shimmer': 'shimmer 2.4s ease-in-out infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(12px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        fadeUp: {
          '0%': { opacity: '0', transform: 'translateY(24px) scale(0.97)' },
          '100%': { opacity: '1', transform: 'translateY(0) scale(1)' },
        },
        scalePop: {
          '0%': { opacity: '0', transform: 'scale(0.85)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        pulseSoft: {
          '0%, 100%': { transform: 'scale(1)', boxShadow: '0 0 0 0 rgba(30, 58, 95, 0.35)' },
          '50%': { transform: 'scale(1.02)', boxShadow: '0 0 0 12px rgba(30, 58, 95, 0)' },
        },
        successCheck: {
          '0%': { opacity: '0', transform: 'scale(0.4)' },
          '60%': { transform: 'scale(1.15)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        slideIn: {
          '0%': { opacity: '0', transform: 'translateX(var(--sz-slide-from, 100%))' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        gridIn: {
          '0%': { opacity: '0', transform: 'translateY(16px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        iconBounce: {
          '0%': { transform: 'scale(1) rotate(0deg)' },
          '40%': { transform: 'scale(1.18) rotate(-6deg)' },
          '70%': { transform: 'scale(0.95) rotate(3deg)' },
          '100%': { transform: 'scale(1) rotate(0deg)' },
        },
        shimmer: {
          '0%, 100%': { opacity: '0.6' },
          '50%': { opacity: '1' },
        },
      },
    },
  },
  plugins: [],
} satisfies Config
